---
title: "Words in time"
author: "Niko Ilomäki"
date: "Wednesday, May 13, 2015"
output: markdown_document
---

```{r, echo=FALSE}
library(dplyr)
find_swe <- function(word,color) {
	temp <- vol %>% filter(Lang=="swe") %>% filter(grepl(word,Text)) %>% group_by(Year) %>% tally() %>% arrange(Year)
	temp <- merge(counts,temp,all=TRUE)
	temp$n[is.na(temp$n)] <- 0
	temp$pct <- temp$n/temp$Swe
	plot(temp$Year,temp$pct,type="l",col=color,ylim=c(0,1),xlab="Year",ylab="Ratio")
}
vol <- readRDS("vol.Rds")
counts <- vol %>% group_by(Year) %>% summarise(Total = n()) %>% arrange(Year)
swedish <- vol %>% filter(Lang=="swe") %>% group_by(Year) %>% summarise(Swe = n()) %>% arrange(Year)
counts <- merge(counts,swedish,all=TRUE)
counts$Swe[is.na(counts$Swe)] <- 0
```

# Use of *glödlampa*

```{r glodlampa, echo=FALSE}
find_swe("glödlamp","blue")
```

# Use of *båglampa*

```{r baglampa, echo=FALSE}
find_swe("båglamp","red")
```

# Use of *janduslampa*

```{r janduslampa, echo=FALSE}
find_swe("janduslamp","green")
```

# Use of *bordslampa*

```{r bordslampa, echo=FALSE}
find_swe("bordslamp","orange")
```

# Use of *normalljus*

```{r normalljus, echo=FALSE}
find_swe("normalljus","purple")
```

# Use of *ljusstyrka*

```{r ljusstyrka, echo=FALSE}
find_swe("ljusstyrk","brown")
```
