library(dplyr)
library(tau)
word <- rapply(df$Text,c)
word <- fixEncoding(word,latin1=TRUE)
word <- tolower(word)
word <- gsub("[.:,;&*-=()/~|'+%]","",word)
word <- gsub("[0-9]","",word)
wframe <- as.data.frame(word)
wframe <- tbl_df(wframe)
freq <- wframe %>% group_by(word) %>% tally(sort=TRUE)
